### ISSUE TITLE
Event bubbling

### ISSUE THREAD

**Issue by elliotdickison** [smooth-code/react-teleporter#7]
## 🚀 Feature Proposal

Bubble events up through the target tree, not the source tree. Or make it an option?

## Motivation

Portals do some [magic to bubble events](https://reactjs.org/docs/portals.html#event-bubbling-through-portals) up through the component tree that calls the portal, not the location where the portal is actually rendered. This is normally what you want with portals (90% of use-cases I've seen are to just dump the target at the end of the document body), but I feel like it may be unexpected behavior for react-teleporter.

## P.S.

Super cool lib, love how simple and powerful it is. Nice work!

**Comment by gregberge** [comment]
Hello @elliotdickison, thanks to raise the subject. I let it opened, if you or other have a specific use-case for this problem, feel free to submit it. Then we would think about a way to fix this.

**Comment by dgdavid** [comment]
Hi all!

> Super cool lib, love how simple and powerful it is. Nice work!

+:100: 

At the [D-Installer](https://github.com/yast/d-installer) project, we have found a use-case:

_When the user clicks on a link in the slide-in sidebar, it must be able to hide itself without using callbacks or shared context_

It's fairly easy to accomplish this thanks to event bubbling. However, it is not as easy with the teleported links since, as it is documented, the event bubbles through the React tree rather than the DOM tree.

Thus, I have opened a PR to make the target aware of events in the teleported content. 

Please have a look to #47 and to the [codesandbox project](https://codesandbox.io/p/sandbox/react-teleporter-bubbling-demo-x3wo4f) illustrating the use-case.

Thank you!
